"""Canonical tool contracts, registry, and configuration policy services."""

from .registry import ToolRegistry, registry, tool_error
from .configuration import (
    CONFIGURABLE_TOOLSETS,
    PLATFORMS,
    apply_mcp_change,
    apply_toolset_change,
    get_effective_configurable_toolsets,
    get_enabled_platforms,
    get_platform_tools,
    get_plugin_toolset_keys,
    get_plugin_toolsets,
    parse_enabled_flag,
    platform_toolset_summary,
    save_platform_tools,
)
from .provider_configuration import (
    detect_active_provider_index,
    is_provider_active,
    needs_configuration_prompt,
    visible_providers,
)
from .token_estimation import ToolTokenEstimator, estimate_tool_tokens
from .toolsets import (
    TOOLSETS,
    create_custom_toolset,
    get_all_toolsets,
    get_default_toolset,
    get_default_tools,
    get_toolset,
    get_toolset_description,
    get_toolset_info,
    is_valid_toolset,
    resolve_toolset,
    validate_toolset,
)

__all__ = [
    "CONFIGURABLE_TOOLSETS",
    "PLATFORMS",
    "ToolRegistry",
    "ToolTokenEstimator",
    "TOOLSETS",
    "apply_mcp_change",
    "apply_toolset_change",
    "get_effective_configurable_toolsets",
    "get_enabled_platforms",
    "get_platform_tools",
    "get_plugin_toolset_keys",
    "get_plugin_toolsets",
    "detect_active_provider_index",
    "estimate_tool_tokens",
    "create_custom_toolset",
    "get_all_toolsets",
    "get_default_toolset",
    "get_default_tools",
    "get_toolset",
    "get_toolset_description",
    "get_toolset_info",
    "is_provider_active",
    "needs_configuration_prompt",
    "is_valid_toolset",
    "parse_enabled_flag",
    "platform_toolset_summary",
    "registry",
    "resolve_toolset",
    "save_platform_tools",
    "tool_error",
    "validate_toolset",
    "visible_providers",
]
