"""Generate the repository Body baseline config from DEFAULT_CONFIG."""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
for import_root in (ROOT, ROOT / "src"):
    if str(import_root) not in sys.path:
        sys.path.insert(0, str(import_root))
REPO_CONFIG_PATH = ROOT / "config.yaml"
HEADER = (
    "# Generated by scripts/sync_repo_config.py from "
    "voidcube.infrastructure.config.configuration.DEFAULT_CONFIG.\n"
    "# This is a repository Body/probe baseline, not the user's runtime config.\n"
    "# User configuration lives at VOIDCUBE_HOME/config.yaml.\n\n"
)


def render_repo_config() -> str:
    from voidcube.infrastructure.config.configuration import DEFAULT_CONFIG

    return HEADER + yaml.safe_dump(
        DEFAULT_CONFIG,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )


def write_repo_config(path: Path = REPO_CONFIG_PATH) -> None:
    content = render_repo_config()
    path = path.resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        dir=str(path.parent),
        prefix=f".{path.stem}_",
        suffix=".tmp",
    )
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    finally:
        temporary_path = Path(temporary_name)
        if temporary_path.exists():
            temporary_path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if config.yaml is not the generated DEFAULT_CONFIG snapshot.",
    )
    args = parser.parse_args()

    expected = render_repo_config()
    if args.check:
        actual = (
            REPO_CONFIG_PATH.read_text(encoding="utf-8")
            if REPO_CONFIG_PATH.is_file()
            else ""
        )
        if actual != expected:
            print(
                "Repository config is stale. Run: "
                "python scripts/sync_repo_config.py"
            )
            return 1
        return 0

    write_repo_config()
    print(f"Updated repository Body baseline: {REPO_CONFIG_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
