"""Supervisor system runtime adapters."""

from .autonomous_executor import (
    AutonomousExecutorPorts,
    autonomous_task_execution_kind,
    autonomous_task_run_id_for_message,
    autonomous_task_toolsets,
    build_autonomous_task_prompt,
)
from .scheduled_tasks import ScheduledTaskStore
from .account_store import (
    AccountStoreSnapshot,
    ParsedCookie,
    PlatformAccount,
    account_for_api,
    cookie_header_for_url,
    cookies_for_url,
    delete_account,
    load_account_store,
    load_accounts,
    missing_required_auth_cookies,
    parse_cookie_string,
    platform_name,
    sanitize_account_label,
    save_account,
    save_account_store,
    verify_account,
)
from .provider_pool_service import (
    CompanionWorkerAssignmentRequest,
    CompanionWorkerAssignmentsRequest,
    ProviderPoolConflictError,
    ProviderPoolEntryRequest,
    ProviderPoolManagedError,
    ProviderPoolProbeError,
    ProviderPoolService,
)
from .autonomous_chain_store import (
    AutonomousChainExecutionLease,
    AutonomousChainExecutionRequest,
    AutonomousChainGitLineage,
    AutonomousChainStore,
    AutonomousChainStoreSnapshot,
    AutonomousChainTask,
    AutonomousChainTaskDecision,
    StaleExecutionLeaseError,
)

__all__ = [
    "AutonomousExecutorPorts",
    "autonomous_task_execution_kind",
    "autonomous_task_run_id_for_message",
    "autonomous_task_toolsets",
    "build_autonomous_task_prompt",
    "ScheduledTaskStore",
    "AccountStoreSnapshot",
    "ParsedCookie",
    "PlatformAccount",
    "account_for_api",
    "cookie_header_for_url",
    "cookies_for_url",
    "delete_account",
    "load_account_store",
    "load_accounts",
    "missing_required_auth_cookies",
    "parse_cookie_string",
    "platform_name",
    "sanitize_account_label",
    "save_account",
    "save_account_store",
    "verify_account",
    "CompanionWorkerAssignmentRequest",
    "CompanionWorkerAssignmentsRequest",
    "ProviderPoolConflictError",
    "ProviderPoolEntryRequest",
    "ProviderPoolManagedError",
    "ProviderPoolProbeError",
    "ProviderPoolService",
    "AutonomousChainExecutionLease",
    "AutonomousChainExecutionRequest",
    "AutonomousChainGitLineage",
    "AutonomousChainStore",
    "AutonomousChainStoreSnapshot",
    "AutonomousChainTask",
    "AutonomousChainTaskDecision",
    "StaleExecutionLeaseError",
]
